[package]
name = "spackle-node-addon"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2.16.6"
napi-derive = "2.16.5"
spackle = { path = ".." }


[build-dependencies]
napi-build = "2.1.3"
