// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod a2ai {
    pub mod spackle {
        /// Host-provided capabilities. The component imports these and the
        /// TypeScript harness implements them (subprocess spawn via Bun.spawn).
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod host {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct CommandResult {
                pub stdout: _rt::Vec<u8>,
                pub stderr: _rt::Vec<u8>,
                pub exit_code: i32,
            }
            impl ::core::fmt::Debug for CommandResult {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("CommandResult")
                        .field("stdout", &self.stdout)
                        .field("stderr", &self.stderr)
                        .field("exit-code", &self.exit_code)
                        .finish()
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Run a command synchronously on behalf of the component.
            /// `args` is a list of arguments (not including the command itself).
            /// `env` is a list of (name, value) pairs — merged with the host
            /// process's environment by the host implementation.
            pub fn run_command(
                cmd: &str,
                args: &[_rt::String],
                cwd: &str,
                env: &[(_rt::String, _rt::String)],
            ) -> Result<CommandResult, _rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 6 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 6
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = cmd;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec2 = args;
                    let len2 = vec2.len();
                    let layout2 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec2.len() * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result2 = if layout2.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout2).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout2);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec2.into_iter().enumerate() {
                        let base = result2
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        {
                            let vec1 = e;
                            let ptr1 = vec1.as_ptr().cast::<u8>();
                            let len1 = vec1.len();
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len1;
                            *base.add(0).cast::<*mut u8>() = ptr1.cast_mut();
                        }
                    }
                    let vec3 = cwd;
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    let vec7 = env;
                    let len7 = vec7.len();
                    let layout7 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec7.len() * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result7 = if layout7.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout7).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout7);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec7.into_iter().enumerate() {
                        let base = result7
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let (t4_0, t4_1) = e;
                            let vec5 = t4_0;
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *base.add(0).cast::<*mut u8>() = ptr5.cast_mut();
                            let vec6 = t4_1;
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr6.cast_mut();
                        }
                    }
                    let ptr8 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "a2ai:spackle/host")]
                    unsafe extern "C" {
                        #[link_name = "run-command"]
                        fn wit_import9(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import9(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import9(
                            ptr0.cast_mut(),
                            len0,
                            result2,
                            len2,
                            ptr3.cast_mut(),
                            len3,
                            result7,
                            len7,
                            ptr8,
                        )
                    };
                    let l10 = i32::from(*ptr8.add(0).cast::<u8>());
                    let result21 = match l10 {
                        0 => {
                            let e = {
                                let l11 = *ptr8
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l12 = *ptr8
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len13 = l12;
                                let l14 = *ptr8
                                    .add(3 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l15 = *ptr8
                                    .add(4 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len16 = l15;
                                let l17 = *ptr8
                                    .add(5 * ::core::mem::size_of::<*const u8>())
                                    .cast::<i32>();
                                CommandResult {
                                    stdout: _rt::Vec::from_raw_parts(l11.cast(), len13, len13),
                                    stderr: _rt::Vec::from_raw_parts(l14.cast(), len16, len16),
                                    exit_code: l17,
                                }
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l18 = *ptr8
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l19 = *ptr8
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len20 = l19;
                                let bytes20 = _rt::Vec::from_raw_parts(
                                    l18.cast(),
                                    len20,
                                    len20,
                                );
                                _rt::string_lift(bytes20)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    if layout2.size() != 0 {
                        _rt::alloc::dealloc(result2.cast(), layout2);
                    }
                    if layout7.size() != 0 {
                        _rt::alloc::dealloc(result7.cast(), layout7);
                    }
                    result21
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod a2ai {
        pub mod spackle {
            /// Primary contract exported to the host. All payloads are JSON strings
            /// so the component can evolve its schemas without churning the WIT.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod api {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_check_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::check(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec3 = (result1.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_check<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_validate_slot_data_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let result2 = T::validate_slot_data(
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec4 = (result2.into_bytes()).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *ptr3.add(0).cast::<*mut u8>() = ptr4.cast_mut();
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_validate_slot_data<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_generate_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let len2 = arg5;
                    let bytes2 = _rt::Vec::from_raw_parts(arg4.cast(), len2, len2);
                    let result3 = T::generate(
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                        _rt::string_lift(bytes2),
                        _rt::bool_lift(arg6 as u8),
                    );
                    let ptr4 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec5 = (result3.into_bytes()).into_boxed_slice();
                    let ptr5 = vec5.as_ptr().cast::<u8>();
                    let len5 = vec5.len();
                    ::core::mem::forget(vec5);
                    *ptr4.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr4.add(0).cast::<*mut u8>() = ptr5.cast_mut();
                    ptr4
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_generate<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                pub trait Guest {
                    /// Validate a project directory: parses spackle.toml, checks slot
                    /// config, validates template references against slot keys.
                    ///
                    /// Returns JSON:
                    ///   on success: `{ "valid": true, "config": { "name", "ignore", "slots", "hooks" } }`
                    ///   on failure: `{ "valid": false, "errors": ["..."] }`
                    ///
                    /// Including the parsed config on success lets the host render forms
                    /// and pre-validate slot values without parsing TOML itself.
                    fn check(project_dir: _rt::String) -> _rt::String;
                    /// Validate slot data against the config loaded from `project-dir`.
                    ///
                    /// `slot-data-json` is a JSON object of `{ slot_key: string_value }`.
                    ///
                    /// Returns JSON:
                    ///   `{ "valid": true }` or `{ "valid": false, "errors": ["..."] }`
                    fn validate_slot_data(
                        project_dir: _rt::String,
                        slot_data_json: _rt::String,
                    ) -> _rt::String;
                    /// Generate a filled project directory at `out-dir`.
                    ///
                    /// Requires:
                    ///   - `project-dir` readable under the WASI preopen grant
                    ///   - `out-dir` NOT to exist — it is created from scratch (matches
                    ///     native `Project::generate` semantics)
                    ///   - `slot-data-json` to validate against the project's slot config
                    ///     (caller should have run `validate-slot-data` first)
                    ///   - `run-hooks = true` causes post-generation hooks to be executed
                    ///     via the host-imported `run-command` function
                    ///
                    /// Returns JSON:
                    ///   `{ "ok": true, "rendered": [...], "hook_results": [...] }`
                    ///   `{ "ok": false, "error": "..." }`
                    fn generate(
                        project_dir: _rt::String,
                        out_dir: _rt::String,
                        slot_data_json: _rt::String,
                        run_hooks: bool,
                    ) -> _rt::String;
                }
                #[doc(hidden)]
                macro_rules! __export_a2ai_spackle_api_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "a2ai:spackle/api#check")] unsafe extern "C" fn export_check(arg0
                        : * mut u8, arg1 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_check_cabi::<$ty > (arg0, arg1) } }
                        #[unsafe (export_name = "cabi_post_a2ai:spackle/api#check")]
                        unsafe extern "C" fn _post_return_check(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_check::<$ty > (arg0)
                        } } #[unsafe (export_name =
                        "a2ai:spackle/api#validate-slot-data")] unsafe extern "C" fn
                        export_validate_slot_data(arg0 : * mut u8, arg1 : usize, arg2 : *
                        mut u8, arg3 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_validate_slot_data_cabi::<$ty >
                        (arg0, arg1, arg2, arg3) } } #[unsafe (export_name =
                        "cabi_post_a2ai:spackle/api#validate-slot-data")] unsafe extern
                        "C" fn _post_return_validate_slot_data(arg0 : * mut u8,) { unsafe
                        { $($path_to_types)*:: __post_return_validate_slot_data::<$ty >
                        (arg0) } } #[unsafe (export_name = "a2ai:spackle/api#generate")]
                        unsafe extern "C" fn export_generate(arg0 : * mut u8, arg1 :
                        usize, arg2 : * mut u8, arg3 : usize, arg4 : * mut u8, arg5 :
                        usize, arg6 : i32,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_generate_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4,
                        arg5, arg6) } } #[unsafe (export_name =
                        "cabi_post_a2ai:spackle/api#generate")] unsafe extern "C" fn
                        _post_return_generate(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_generate::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_a2ai_spackle_api_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::vec::Vec;
    pub use alloc_crate::string::String;
    pub use alloc_crate::alloc;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_spackle_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::a2ai::spackle::api::__export_a2ai_spackle_api_cabi!($ty with_types_in
        $($path_to_types_root)*:: exports::a2ai::spackle::api);
    };
}
#[doc(inline)]
pub(crate) use __export_spackle_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:a2ai:spackle:spackle:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 470] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd8\x02\x01A\x02\x01\
A\x04\x01B\x09\x01p}\x01r\x03\x06stdout\0\x06stderr\0\x09exit-codez\x04\0\x0ecom\
mand-result\x03\0\x01\x01ps\x01o\x02ss\x01p\x04\x01j\x01\x02\x01s\x01@\x04\x03cm\
ds\x04args\x03\x03cwds\x03env\x05\0\x06\x04\0\x0brun-command\x01\x07\x03\0\x11a2\
ai:spackle/host\x05\0\x01B\x06\x01@\x01\x0bproject-dirs\0s\x04\0\x05check\x01\0\x01\
@\x02\x0bproject-dirs\x0eslot-data-jsons\0s\x04\0\x12validate-slot-data\x01\x01\x01\
@\x04\x0bproject-dirs\x07out-dirs\x0eslot-data-jsons\x09run-hooks\x7f\0s\x04\0\x08\
generate\x01\x02\x04\0\x10a2ai:spackle/api\x05\x01\x04\0\x14a2ai:spackle/spackle\
\x04\0\x0b\x0d\x01\0\x07spackle\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0d\
wit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
