name: Snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
      - "docs/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      release: false
    secrets:
      GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
      POLYJUICE_DEPLOY_KEY: ${{ secrets.POLYJUICE_DEPLOY_KEY }}
